### ISSUE TITLE
☂️ Support asynchronous methods that report progress

### ISSUE THREAD

**Issue by halildurmus** [halildurmus/dartwinrt#209]
WinRT has four types of asynchronous operation objects:

- [x] [IAsyncAction](https://learn.microsoft.com/en-us/uwp/api/windows.foundation.iasyncaction)
- [ ] [IAsyncActionWithProgress&lt;TProgress>](https://learn.microsoft.com/en-us/uwp/api/windows.foundation.iasyncactionwithprogress-1)
- [x] [IAsyncOperation&lt;TResult>](https://learn.microsoft.com/en-us/uwp/api/windows.foundation.iasyncoperation-1)
- [ ] [IAsyncOperationWithProgress<TResult, TProgress>](https://learn.microsoft.com/en-us/uwp/api/windows.foundation.iasyncoperationwithprogress-2)

Currently, only the `IAsyncAction` and `IAsyncOperation` objects are supported.
